/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.dynamos.image.analysis;

import java.util.*;
import org.dynamos.image.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    public void caseAImage(AImage node)
    {
        defaultCase(node);
    }

    public void caseAObjectDefinition(AObjectDefinition node)
    {
        defaultCase(node);
    }

    public void caseASlots(ASlots node)
    {
        defaultCase(node);
    }

    public void caseAFunctions(AFunctions node)
    {
        defaultCase(node);
    }

    public void caseAFunctionDefinition(AFunctionDefinition node)
    {
        defaultCase(node);
    }

    public void caseARequiredParameters(ARequiredParameters node)
    {
        defaultCase(node);
    }

    public void caseAOpcodes(AOpcodes node)
    {
        defaultCase(node);
    }

    public void caseTColon(TColon node)
    {
        defaultCase(node);
    }

    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    public void caseTOpenBrace(TOpenBrace node)
    {
        defaultCase(node);
    }

    public void caseTCloseBrace(TCloseBrace node)
    {
        defaultCase(node);
    }

    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
