/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.dynamos.image.analysis;

import java.util.*;
import org.dynamos.image.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPImage().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAImage(AImage node)
    {
        defaultIn(node);
    }

    public void outAImage(AImage node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAImage(AImage node)
    {
        inAImage(node);
        {
            List<PObjectDefinition> copy = new ArrayList<PObjectDefinition>(node.getObjectDefinition());
            for(PObjectDefinition e : copy)
            {
                e.apply(this);
            }
        }
        outAImage(node);
    }

    public void inASlotObjectDefinition(ASlotObjectDefinition node)
    {
        defaultIn(node);
    }

    public void outASlotObjectDefinition(ASlotObjectDefinition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASlotObjectDefinition(ASlotObjectDefinition node)
    {
        inASlotObjectDefinition(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getSlots() != null)
        {
            node.getSlots().apply(this);
        }
        if(node.getFunctions() != null)
        {
            node.getFunctions().apply(this);
        }
        outASlotObjectDefinition(node);
    }

    public void inAReferenceObjectDefinition(AReferenceObjectDefinition node)
    {
        defaultIn(node);
    }

    public void outAReferenceObjectDefinition(AReferenceObjectDefinition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAReferenceObjectDefinition(AReferenceObjectDefinition node)
    {
        inAReferenceObjectDefinition(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getDollar() != null)
        {
            node.getDollar().apply(this);
        }
        if(node.getReferences() != null)
        {
            node.getReferences().apply(this);
        }
        outAReferenceObjectDefinition(node);
    }

    public void inAContinueReferences(AContinueReferences node)
    {
        defaultIn(node);
    }

    public void outAContinueReferences(AContinueReferences node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAContinueReferences(AContinueReferences node)
    {
        inAContinueReferences(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getFullstop() != null)
        {
            node.getFullstop().apply(this);
        }
        if(node.getReferences() != null)
        {
            node.getReferences().apply(this);
        }
        outAContinueReferences(node);
    }

    public void inAEndReferences(AEndReferences node)
    {
        defaultIn(node);
    }

    public void outAEndReferences(AEndReferences node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEndReferences(AEndReferences node)
    {
        inAEndReferences(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getDollar() != null)
        {
            node.getDollar().apply(this);
        }
        outAEndReferences(node);
    }

    public void inASlots(ASlots node)
    {
        defaultIn(node);
    }

    public void outASlots(ASlots node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASlots(ASlots node)
    {
        inASlots(node);
        if(node.getOpenBrace() != null)
        {
            node.getOpenBrace().apply(this);
        }
        if(node.getImage() != null)
        {
            node.getImage().apply(this);
        }
        if(node.getCloseBrace() != null)
        {
            node.getCloseBrace().apply(this);
        }
        outASlots(node);
    }

    public void inAFunctions(AFunctions node)
    {
        defaultIn(node);
    }

    public void outAFunctions(AFunctions node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFunctions(AFunctions node)
    {
        inAFunctions(node);
        if(node.getOpenBrace() != null)
        {
            node.getOpenBrace().apply(this);
        }
        {
            List<PFunctionDefinition> copy = new ArrayList<PFunctionDefinition>(node.getFunctionDefinition());
            for(PFunctionDefinition e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getCloseBrace() != null)
        {
            node.getCloseBrace().apply(this);
        }
        outAFunctions(node);
    }

    public void inAFunctionDefinition(AFunctionDefinition node)
    {
        defaultIn(node);
    }

    public void outAFunctionDefinition(AFunctionDefinition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFunctionDefinition(AFunctionDefinition node)
    {
        inAFunctionDefinition(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getRequiredParameters() != null)
        {
            node.getRequiredParameters().apply(this);
        }
        if(node.getOpcodes() != null)
        {
            node.getOpcodes().apply(this);
        }
        outAFunctionDefinition(node);
    }

    public void inARequiredParameters(ARequiredParameters node)
    {
        defaultIn(node);
    }

    public void outARequiredParameters(ARequiredParameters node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARequiredParameters(ARequiredParameters node)
    {
        inARequiredParameters(node);
        if(node.getOpenBrace() != null)
        {
            node.getOpenBrace().apply(this);
        }
        {
            List<PRequiredParameter> copy = new ArrayList<PRequiredParameter>(node.getRequiredParameter());
            for(PRequiredParameter e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getCloseBrace() != null)
        {
            node.getCloseBrace().apply(this);
        }
        outARequiredParameters(node);
    }

    public void inARequiredParameter(ARequiredParameter node)
    {
        defaultIn(node);
    }

    public void outARequiredParameter(ARequiredParameter node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARequiredParameter(ARequiredParameter node)
    {
        inARequiredParameter(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getFullstop() != null)
        {
            node.getFullstop().apply(this);
        }
        outARequiredParameter(node);
    }

    public void inAOpcodes(AOpcodes node)
    {
        defaultIn(node);
    }

    public void outAOpcodes(AOpcodes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOpcodes(AOpcodes node)
    {
        inAOpcodes(node);
        if(node.getOpenBrace() != null)
        {
            node.getOpenBrace().apply(this);
        }
        {
            List<POpcode> copy = new ArrayList<POpcode>(node.getOpcode());
            for(POpcode e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getCloseBrace() != null)
        {
            node.getCloseBrace().apply(this);
        }
        outAOpcodes(node);
    }

    public void inAOpcode(AOpcode node)
    {
        defaultIn(node);
    }

    public void outAOpcode(AOpcode node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOpcode(AOpcode node)
    {
        inAOpcode(node);
        if(node.getOpcodeId() != null)
        {
            node.getOpcodeId().apply(this);
        }
        if(node.getFullstop() != null)
        {
            node.getFullstop().apply(this);
        }
        outAOpcode(node);
    }

    public void inANumberOpcodeId(ANumberOpcodeId node)
    {
        defaultIn(node);
    }

    public void outANumberOpcodeId(ANumberOpcodeId node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberOpcodeId(ANumberOpcodeId node)
    {
        inANumberOpcodeId(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        if(node.getOpcodeParameter() != null)
        {
            node.getOpcodeParameter().apply(this);
        }
        outANumberOpcodeId(node);
    }

    public void inAOpcodeOpcodeId(AOpcodeOpcodeId node)
    {
        defaultIn(node);
    }

    public void outAOpcodeOpcodeId(AOpcodeOpcodeId node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOpcodeOpcodeId(AOpcodeOpcodeId node)
    {
        inAOpcodeOpcodeId(node);
        if(node.getMnemonic() != null)
        {
            node.getMnemonic().apply(this);
        }
        if(node.getOpcodeParameter() != null)
        {
            node.getOpcodeParameter().apply(this);
        }
        outAOpcodeOpcodeId(node);
    }

    public void inASymbolOpcodeParameter(ASymbolOpcodeParameter node)
    {
        defaultIn(node);
    }

    public void outASymbolOpcodeParameter(ASymbolOpcodeParameter node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASymbolOpcodeParameter(ASymbolOpcodeParameter node)
    {
        inASymbolOpcodeParameter(node);
        if(node.getEquals() != null)
        {
            node.getEquals().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outASymbolOpcodeParameter(node);
    }

    public void inAValueOpcodeParameter(AValueOpcodeParameter node)
    {
        defaultIn(node);
    }

    public void outAValueOpcodeParameter(AValueOpcodeParameter node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValueOpcodeParameter(AValueOpcodeParameter node)
    {
        inAValueOpcodeParameter(node);
        if(node.getHash() != null)
        {
            node.getHash().apply(this);
        }
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outAValueOpcodeParameter(node);
    }

    public void inAEmptyOpcodeParameter(AEmptyOpcodeParameter node)
    {
        defaultIn(node);
    }

    public void outAEmptyOpcodeParameter(AEmptyOpcodeParameter node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyOpcodeParameter(AEmptyOpcodeParameter node)
    {
        inAEmptyOpcodeParameter(node);
        outAEmptyOpcodeParameter(node);
    }
}
