/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.dynamos.image.node;

import org.dynamos.image.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyOpcodeParameter extends POpcodeParameter
{

    public AEmptyOpcodeParameter()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyOpcodeParameter();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyOpcodeParameter(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
