/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.dynamos.image.node;

import org.dynamos.image.analysis.*;

@SuppressWarnings("nls")
public final class AFunctionDefinition extends PFunctionDefinition
{
    private TId _id_;
    private PRequiredParameters _requiredParameters_;
    private POpcodes _opcodes_;

    public AFunctionDefinition()
    {
        // Constructor
    }

    public AFunctionDefinition(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PRequiredParameters _requiredParameters_,
        @SuppressWarnings("hiding") POpcodes _opcodes_)
    {
        // Constructor
        setId(_id_);

        setRequiredParameters(_requiredParameters_);

        setOpcodes(_opcodes_);

    }

    @Override
    public Object clone()
    {
        return new AFunctionDefinition(
            cloneNode(this._id_),
            cloneNode(this._requiredParameters_),
            cloneNode(this._opcodes_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionDefinition(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PRequiredParameters getRequiredParameters()
    {
        return this._requiredParameters_;
    }

    public void setRequiredParameters(PRequiredParameters node)
    {
        if(this._requiredParameters_ != null)
        {
            this._requiredParameters_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._requiredParameters_ = node;
    }

    public POpcodes getOpcodes()
    {
        return this._opcodes_;
    }

    public void setOpcodes(POpcodes node)
    {
        if(this._opcodes_ != null)
        {
            this._opcodes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opcodes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._requiredParameters_)
            + toString(this._opcodes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._requiredParameters_ == child)
        {
            this._requiredParameters_ = null;
            return;
        }

        if(this._opcodes_ == child)
        {
            this._opcodes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._requiredParameters_ == oldChild)
        {
            setRequiredParameters((PRequiredParameters) newChild);
            return;
        }

        if(this._opcodes_ == oldChild)
        {
            setOpcodes((POpcodes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
