/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.dynamos.image.node;

import java.util.*;
import org.dynamos.image.analysis.*;

@SuppressWarnings("nls")
public final class AImage extends PImage
{
    private final LinkedList<PObjectDefinition> _objectDefinition_ = new LinkedList<PObjectDefinition>();

    public AImage()
    {
        // Constructor
    }

    public AImage(
        @SuppressWarnings("hiding") List<PObjectDefinition> _objectDefinition_)
    {
        // Constructor
        setObjectDefinition(_objectDefinition_);

    }

    @Override
    public Object clone()
    {
        return new AImage(
            cloneList(this._objectDefinition_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImage(this);
    }

    public LinkedList<PObjectDefinition> getObjectDefinition()
    {
        return this._objectDefinition_;
    }

    public void setObjectDefinition(List<PObjectDefinition> list)
    {
        this._objectDefinition_.clear();
        this._objectDefinition_.addAll(list);
        for(PObjectDefinition e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._objectDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._objectDefinition_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PObjectDefinition> i = this._objectDefinition_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PObjectDefinition) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
