/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.dynamos.image.node;

import org.dynamos.image.analysis.*;

@SuppressWarnings("nls")
public final class AOpcodeOpcodeId extends POpcodeId
{
    private TMnemonic _mnemonic_;
    private POpcodeParameter _opcodeParameter_;

    public AOpcodeOpcodeId()
    {
        // Constructor
    }

    public AOpcodeOpcodeId(
        @SuppressWarnings("hiding") TMnemonic _mnemonic_,
        @SuppressWarnings("hiding") POpcodeParameter _opcodeParameter_)
    {
        // Constructor
        setMnemonic(_mnemonic_);

        setOpcodeParameter(_opcodeParameter_);

    }

    @Override
    public Object clone()
    {
        return new AOpcodeOpcodeId(
            cloneNode(this._mnemonic_),
            cloneNode(this._opcodeParameter_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpcodeOpcodeId(this);
    }

    public TMnemonic getMnemonic()
    {
        return this._mnemonic_;
    }

    public void setMnemonic(TMnemonic node)
    {
        if(this._mnemonic_ != null)
        {
            this._mnemonic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mnemonic_ = node;
    }

    public POpcodeParameter getOpcodeParameter()
    {
        return this._opcodeParameter_;
    }

    public void setOpcodeParameter(POpcodeParameter node)
    {
        if(this._opcodeParameter_ != null)
        {
            this._opcodeParameter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opcodeParameter_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mnemonic_)
            + toString(this._opcodeParameter_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mnemonic_ == child)
        {
            this._mnemonic_ = null;
            return;
        }

        if(this._opcodeParameter_ == child)
        {
            this._opcodeParameter_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mnemonic_ == oldChild)
        {
            setMnemonic((TMnemonic) newChild);
            return;
        }

        if(this._opcodeParameter_ == oldChild)
        {
            setOpcodeParameter((POpcodeParameter) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
