/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.dynamos.image.node;

import org.dynamos.image.analysis.*;

@SuppressWarnings("nls")
public final class ASlots extends PSlots
{
    private TOpenBrace _openBrace_;
    private PImage _image_;
    private TCloseBrace _closeBrace_;

    public ASlots()
    {
        // Constructor
    }

    public ASlots(
        @SuppressWarnings("hiding") TOpenBrace _openBrace_,
        @SuppressWarnings("hiding") PImage _image_,
        @SuppressWarnings("hiding") TCloseBrace _closeBrace_)
    {
        // Constructor
        setOpenBrace(_openBrace_);

        setImage(_image_);

        setCloseBrace(_closeBrace_);

    }

    @Override
    public Object clone()
    {
        return new ASlots(
            cloneNode(this._openBrace_),
            cloneNode(this._image_),
            cloneNode(this._closeBrace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASlots(this);
    }

    public TOpenBrace getOpenBrace()
    {
        return this._openBrace_;
    }

    public void setOpenBrace(TOpenBrace node)
    {
        if(this._openBrace_ != null)
        {
            this._openBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._openBrace_ = node;
    }

    public PImage getImage()
    {
        return this._image_;
    }

    public void setImage(PImage node)
    {
        if(this._image_ != null)
        {
            this._image_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._image_ = node;
    }

    public TCloseBrace getCloseBrace()
    {
        return this._closeBrace_;
    }

    public void setCloseBrace(TCloseBrace node)
    {
        if(this._closeBrace_ != null)
        {
            this._closeBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closeBrace_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._openBrace_)
            + toString(this._image_)
            + toString(this._closeBrace_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._openBrace_ == child)
        {
            this._openBrace_ = null;
            return;
        }

        if(this._image_ == child)
        {
            this._image_ = null;
            return;
        }

        if(this._closeBrace_ == child)
        {
            this._closeBrace_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._openBrace_ == oldChild)
        {
            setOpenBrace((TOpenBrace) newChild);
            return;
        }

        if(this._image_ == oldChild)
        {
            setImage((PImage) newChild);
            return;
        }

        if(this._closeBrace_ == oldChild)
        {
            setCloseBrace((TCloseBrace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
