/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.dynamos.image.parser;

import org.dynamos.image.node.*;
import org.dynamos.image.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 0;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 1;
    }

    @Override
    public void caseTOpenBrace(@SuppressWarnings("unused") TOpenBrace node)
    {
        this.index = 2;
    }

    @Override
    public void caseTCloseBrace(@SuppressWarnings("unused") TCloseBrace node)
    {
        this.index = 3;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 4;
    }
}
